---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nestjs
  namespace: k8s-github-actions
  labels:
    app: hello-world-nestjs
spec:
  selector:
    matchLabels:
      app: hello-world-nestjs
  template:
    metadata:
      labels:
        app: hello-world-nestjs
    spec:
      containers:
        - name: hello-world-nestjs
          image: hello-world/hello-world-nestjs
          imagePullPolicy: Always
          env:
            - name: MONGO__URI
              valueFrom:
                secretKeyRef:
                  key: MONGODB_URI
                  name: hw-secrets
          ports:
            - containerPort: 3000
              name: public
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m